/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardComprovativoRouteImport } from './routes/dashboard.comprovativo'

const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComprovativoRoute = DashboardComprovativoRouteImport.update({
  id: '/comprovativo',
  path: '/comprovativo',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technicians': typeof TechniciansRoute
  '/dashboard/comprovativo': typeof DashboardComprovativoRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technicians': typeof TechniciansRoute
  '/dashboard/comprovativo': typeof DashboardComprovativoRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technicians': typeof TechniciansRoute
  '/dashboard/comprovativo': typeof DashboardComprovativoRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/dashboard'
    | '/planos'
    | '/sitemap.xml'
    | '/technicians'
    | '/dashboard/comprovativo'
    | '/dashboard/perfil'
    | '/dashboard/portfolio'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/planos'
    | '/sitemap.xml'
    | '/technicians'
    | '/dashboard/comprovativo'
    | '/dashboard/perfil'
    | '/dashboard/portfolio'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contacto'
    | '/dashboard'
    | '/planos'
    | '/sitemap.xml'
    | '/technicians'
    | '/dashboard/comprovativo'
    | '/dashboard/perfil'
    | '/dashboard/portfolio'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PlanosRoute: typeof PlanosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechniciansRoute: typeof TechniciansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/comprovativo': {
      id: '/dashboard/comprovativo'
      path: '/comprovativo'
      fullPath: '/dashboard/comprovativo'
      preLoaderRoute: typeof DashboardComprovativoRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardComprovativoRoute: typeof DashboardComprovativoRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardComprovativoRoute: DashboardComprovativoRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PlanosRoute: PlanosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechniciansRoute: TechniciansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
